name: mysql_connector
description: MySQL Connector for Dart
version: 0.0.0
repository: https://github.com/dart-stack/mysql_connector

environment:
  sdk: ^3.2.4

dependencies:
  benchmark: ^0.3.0
  collection: ^1.18.0
  crypto: ^3.0.3
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
